### ISSUE TITLE
Which node version do you use?

### ISSUE THREAD

**Issue by ChainCoderX** [saad-s/uniswap-uni-router-permit2#5]
I got the following error;

> universal-router@1.0.0 start
> node src/index.js

(node:2215036) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
/home/wuban/uniswap-uni-router-permit2/node_modules/@ethersproject/logger/lib/index.js:238
        var error = new Error(message);
                    ^

Error: invalid hexlify value (argument="value", value="", code=INVALID_ARGUMENT, version=bytes/5.7.0)
    at Logger.makeError (/home/wuban/uniswap-uni-router-permit2/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/wuban/uniswap-uni-router-permit2/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/home/wuban/uniswap-uni-router-permit2/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at hexlify (/home/wuban/uniswap-uni-router-permit2/node_modules/@ethersproject/bytes/lib/index.js:200:19)
    at new SigningKey (/home/wuban/uniswap-uni-router-permit2/node_modules/@ethersproject/signing-key/lib/index.js:20:82)
    at new Wallet (/home/wuban/uniswap-uni-router-permit2/node_modules/@ethersproject/wallet/lib/index.js:120:36)
    at getSigner (file:///home/wuban/uniswap-uni-router-permit2/src/constants.js:14:10)
    at file:///home/wuban/uniswap-uni-router-permit2/src/index.js:23:22 {
  reason: 'invalid hexlify value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: ''
}

Node.js v18.20.0

**Comment by saad-s** [comment]
I believe I was using v18.x but your issue looks like you are missing `.env` file. 

do the following 
```
cp .env.example .env
```

and fill the required values in .env and then run the script either by `node src/index.js` or `npm run start`

Another thing to note is that Goerli is EOL'd and replaced by Sepolia so set CHAIN_ID and RPC_URL accrodingly. Maybe contract addresses in constants also need to be updated.
